import "./globals.css";
import Footer from "../components/Footer";
import ThemeWrapper from "../components/ThemeWrapper";
import ShowLogIn from "../components/ShowLogIn";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <ThemeWrapper>
            {children}
            <Footer />
            <ShowLogIn />
          </ThemeWrapper>
      </body>
    </html>
  )
}
