import "./globals.css";
import Footer from "../components/Footer";
import ThemeWrapper from "../components/ThemeWrapper";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
          <ThemeWrapper>
            {children}
            <Footer />
          </ThemeWrapper>
      </body>
    </html>
  )
}
